Fix rpc-error due to quick transaction lookup
This pr addresses an error that occurs due to rpc client
looking up the transaction right before it's on chain .
Error: Transient error: Implementation error: Obtained failure status(500): Internal Server Error

The delay introduced allows the transaction to broadcasted on chain before the lookup

fix format issue

fix long pooling test

Implement pooling mechanism for transaction check

Implement pooling mechanism for transaction check

fix rpc error

fix rpc error

fix lint error